INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Fazer novas amizades','', '4', '2', '1'),
(null,'Operação post-it','', '4', '2', '1'),
(null,'Usar transporte público','', '4', '2', '1'),
(null,'Elogiar uma pessoa por dia','', '4', '2', '1'),
(null,'Ajudar uma pessoa por dia','', '4', '2', '1'),
(null,'Presentear pessoas diferentes','', '4', '2', '1'),
(null,'Escrever texto/ligar para agradecer parente/amigo antigo','', '4', '2', '1'),
(null,'Cumprimentar estranhos','', '4', '2', '1'),
(null,'Emanar cura e amor','', '4', '2', '1'),
(null,'Fazer caridade através de serviço presencial','', '4', '2', '1'),
(null,'Assistir filme que traga autorreflexão com amigos/familiares','', '4', '2', '1'),
(null,'Listar atividades que gosta de fazer','', '4', '2', '1'),
(null,'Listar críticas das pessoas sobre nós','', '4', '2', '1'),
(null,'Listar o que incomoda nos outros','', '4', '2', '1'),
(null,'Fazer carta de gratidão para pessoas específicas','', '4', '2', '1'),
(null,'Fazer surpresa para parceiro ou familiar','', '4', '2', '1'),
(null,'Dar massagens grátis','', '4', '2', '1'),
(null,'Demonstrar amor, afeto e carinho em público','', '4', '2', '1'),
(null,'Sorrir para pessoas no trânsito/transporte público','', '4', '2', '1'),
(null,'Fazer uma atividade que outra pessoa goste junto com ela','', '4', '2', '1'),
(null,'Mudar o que nos criticam se for lógico','', '4', '1', '1'),
(null,'Mudar o que incomoda nos outros em nós','', '4', '1', '1'),
(null,'Cortar ou reduzir contato de pessoas de má influência/círculos desnecessários','', '4', '1', '1'),
(null,'Respirar fundo antes de responder/agir','', '4', '1', '1'),
(null,'Adotar ataques do cônjuge como autodesafios de mudança','', '4', '1', '1'),
(null,'Servir na casa da sogra/ nora/conhecidos','', '4', '1', '1'),
(null,'Tirar sapato quando chegar em casa','', '4', '1', '1'),
(null,'Oferecer-se para fazer favores ao cônjuge','', '4', '1', '1'),
(null,'Pedir desculpas','', '4', '3', '1'),
(null,'Criar intenção de parceiro ideal','', '4', '3', '1'),
(null,'Adotar dieta vegetariana/vegana por amor aos animais','', '4', '3', '1'),
(null,'Ser cortez e amável com quem não gosta ou tem conflitos','', '4', '3', '1'),
(null,'Se questionar: Se você fosse o amor, o que o amor faria?','', '4', '3', '1'),
(null,'Reunir a família sem motivo especial','', '4', '3', '1'),
(null,'Enviar uma mensagem motivadora por dia para pessoas diferentes','', '4', '3', '1'),
(null,'Identificar líderes criativos','', '4', '1', '1'),
(null,'Entrosar equipes','', '4', '2', '1'),
(null,'Criar plano de capacitação e desenvolvimento','', '4', '2', '1'),
(null,'Implementar cultura de feedbacks','', '4', '2', '1'),
(null,'Premiar ou parabenizar pessoas em destaque','', '4', '2', '1'),
(null,'Criar job description','', '4', '2', '1'),
(null,'Criar estratégias de relacionamento com o cliente','', '4', '2', '1'),
(null,'Minimizar conflitos','', '4', '1', '1'),
(null,'Realizar pequenas reuniões de ideias','', '4', '2', '1'),
(null,'Ajudar o colega nos problemas','', '4', '3', '1'),
(null,'Aumentar a proatividade','', '4', '1', '1'),
(null,'Oferecer ajuda','', '4', '1', '1'),
(null,'Escutar as pessoas com atenção e abertura','', '4', '1', '1'),
(null,'Buscar se interessar por assuntos que não geram interesse momentâneo','', '4', '1', '1'),
(null,'Estudar sobre liderança / influência / marketing','', '4', '2', '1'),
(null,'Realizar treinamento comportamental / qualidade de vida / integração','', '4', '3', '1')