INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Fazer esportes não competitivos','', '3', '2', '1'),
(null,'Fazer uma coisa diferente com a mão esquerda','', '3', '2', '1'),
(null,'Listar habilidades que faz bem','', '3', '2', '1'),
(null,'Seguir as regras de trânsito','', '3', '2', '1'),
(null,'Fazer tarefas/organizar a casa  (arrumar a cama, lavar a louça)','', '3', '2', '1'),
(null,'Abrir e-mail em horas específicas','', '3', '2', '1'),
(null,'Jogar Xadrez / Palavras cruzadas / Sudoku / Cubo Mágico','', '3', '2', '1'),
(null,'Divulgar trabalho/empresa/cargo/currículo','', '3', '2', '1'),
(null,'Fazer coisas ao mesmo tempo (lavar cabeça e escovar dentes)','', '3', '2', '1'),
(null,'Terminar projetos atrasados','', '3', '2', '1'),
(null,'Iniciar novos projetos','', '3', '2', '1'),
(null,'Ser pontual','', '3', '2', '1'),
(null,'Arrumar guarda-roupas/mesa/carro e se desfazer de coisas antigas','', '3', '2', '1'),
(null,'Lavar carro','', '3', '2', '1'),
(null,'Colocar mais flores e plantas em seus ambientes','', '3', '2', '1'),
(null,'Limpar a sujeira de outras pessoas','', '3', '2', '1'),
(null,'Reciclar o seu lixo','', '3', '2', '1'),
(null,'Correr mais riscos calculados','', '3', '2', '1'),
(null,'Não fazer hora extra no trabalho','', '3', '1', '1'),
(null,'Anotar e filtrar ideias','', '3', '1', '1'),
(null,'Dar passagem no trânsito','', '3', '1', '1'),
(null,'Cortar jogos','', '3', '1', '1'),
(null,'Eliminar competitividade nos esportes','', '3', '1', '1'),
(null,'Aprender uma nova habilidade','', '3', '1', '1'),
(null,'Cavar um buraco com pá (perda do sentido - gratidão)','', '3', '1', '1'),
(null,'Ficar ocioso','', '3', '1', '1'),
(null,'Parar de usar relógio','', '3', '1', '1'),
(null,'Sempre dar passagem para estranhos','', '3', '1', '1'),
(null,'Segurar a porta para estranhos, conhecidos e familiares','', '3', '1', '1'),
(null,'Parar de se olhar no espelho','', '3', '1', '1'),
(null,'Estudar outra língua','', '3', '3', '1'),
(null,'Doar roupas','', '3', '3', '1'),
(null,'Mudar lugar dos aplicativos no celular','', '3', '3', '1'),
(null,'Não usar poder para conforto','', '3', '3', '1'),
(null,'Fazer planejamento de rotina com ações e descansos','', '3', '3', '1'),
(null,'Permitir que o outro ganhe','', '3', '1', '1'),
(null,'Realizar processos de maneira mais rápida/mais qualidade/mais eficiente','', '3', '2', '1'),
(null,'Criar processos claros','', '3', '2', '1'),
(null,'Criar cronograma ou fluxograma','', '3', '2', '1'),
(null,'Desenvolver expertise de mercado','', '3', '1', '1'),
(null,'Montar plano estratégico','', '3', '2', '1'),
(null,'Estudar sobre processos / produção / otimização / qualidade','', '3', '1', '1'),
(null,'Implementar plano de qualidade','', '3', '2', '1'),
(null,'Aumentar atenção para diminuir retrabalho','', '3', '1', '1'),
(null,'Criar planejamento de atividades semanal','', '3', '2', '1'),
(null,'Realizar treinamentos técnicos','', '3', '3', '1'),
(null,'Organizar o tempo, listar onde investe o tempo','', '3', '2', '1')