INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Dar presentes','', '2', '2', '1'),
(null,'Dar presentes inusitados (nome na estrela, terra e sementes, etc)','', '2', '2', '1'),
(null,'Mastigar mais vezes','', '2', '2', '1'),
(null,'Ler um livro por prazer','', '2', '2', '1'),
(null,'Listar o que incomoda em outras pessoas','', '2', '2', '1'),
(null,'Não mexer no celular enquanto dirige','', '2', '2', '1'),
(null,'Experimentar um sabor novo por dia','', '2', '2', '1'),
(null,'Usar roupas com cores mais alegres','', '2', '2', '1'),
(null,'Inserir cores positivas em ambientes que convive','', '2', '2', '1'),
(null,'Guardar todas as moedas que tiver em um cofrinho','', '2', '2', '1'),
(null,'Montar lego, quebra-cabeças ou similares','', '2', '2', '1'),
(null,'Comprar roupas intímas novas (estímulo sensual)','', '2', '2', '1'),
(null,'Andar de bicicleta','', '2', '2', '1'),
(null,'Pintar a unha de cores fortes','', '2', '2', '1'),
(null,'Fazer controle financeiro','', '2', '1', '1'),
(null,'Anotar hábitos','', '2', '1', '1'),
(null,'Diminuir tempo no banho','', '2', '1', '1'),
(null,'Reservar tempo para si mesmo fazer o que quiser','', '2', '1', '1'),
(null,'Comer menos','', '2', '1', '1'),
(null,'Cortar luxos / supérfluos','', '2', '1', '1'),
(null,'Comer de olhos fechados','', '2', '1', '1'),
(null,'Economizar / gastar menos','', '2', '1', '1'),
(null,'Ficar sem acessar redes sociais','', '2', '1', '1'),
(null,'Cortar sexo por um período','', '2', '1', '1'),
(null,'Cortar pornografia / masturbação','', '2', '1', '1'),
(null,'Parar de ver TV / rádio / notícias','', '2', '1', '1'),
(null,'Cortar saídas a bares, baladas e house parties','', '2', '1', '1'),
(null,'Cortar entretenimentos','', '2', '1', '1'),
(null,'Suportar dor sem reclamar','', '2', '3', '1'),
(null,'Cortar maquiagem','', '2', '3', '1'),
(null,'Cortar perfumes','', '2', '3', '1'),
(null,'Cortar corrupções (download ilegal, furar fila, atestado falso, etc)','', '2', '3', '1'),
(null,'Comprar apenas à vista','', '2', '3', '1'),
(null,'Separar 10% da sua renda para caridade','', '2', '3', '1'),
(null,'Visitar grupos de networking','', '2', '2', '1'),
(null,'Prospectar novos mercados','', '2', '2', '1'),
(null,'Observar concorrência/outras áreas','', '2', '1', '1'),
(null,'Otimizar metas','', '2', '2', '1'),
(null,'Criar plano de negócios/plano de carreira','', '2', '2', '1'),
(null,'Buscar novas parcerias','', '2', '2', '1'),
(null,'Fazer um mapa de ideias e incluir as viáveis em lista de prioridades','', '2', '2', '1'),
(null,'Estudar sobre mercado de atuação / vendas / networking / inovação','', '2', '1', '1'),
(null,'Realizar treinamentos de venda / estratégias de negociação','', '2', '3', '1')