INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Escrever pensamentos','', '6', '2', '1'),
(null,'Orar ao divino','', '6', '2', '1'),
(null,'Estudar desenvolvimento pessoal','', '6', '2', '1'),
(null,'Assistir filme que traga autorreflexão','', '6', '2', '1'),
(null,'Consumir arte clássica','', '6', '2', '1'),
(null,'Perdoar a si mesmo e quem te magoou','', '6', '2', '1'),
(null,'Perdoar relação com o dinheiro (erros, traumas, pessoas, situações)','', '6', '2', '1'),
(null,'Praticar artes marciais','', '6', '2', '1'),
(null,'Separar e levar materiais recicláveis para coleta','', '6', '2', '1'),
(null,'Salvar a vida de insetos','', '6', '2', '1'),
(null,'Aprender uma palavra nova por dia','', '6', '2', '1'),
(null,'Estudar pessoas vencedoras','', '6', '2', '1'),
(null,'Ouvir música instrumental','', '6', '1', '1'),
(null,'Meditar','', '6', '1', '1'),
(null,'Observar pensamentos','', '6', '1', '1'),
(null,'Observar ideias e não se envolver com elas','', '6', '1', '1'),
(null,'Tomar banho de cachoeira','', '6', '1', '1'),
(null,'Cortar arte pop','', '6', '1', '1'),
(null,'Anotar sonhos','', '6', '1', '1'),
(null,'Ficar ocioso','', '6', '1', '1'),
(null,'Colocar intenção em sua própria filosofia de vida (missão, visão e valores)','', '6', '1', '1'),
(null,'Fazer um inventário moral minucioso sobre si mesmo','', '6', '1', '1'),
(null,'Criar uma lista do que acredita que precisa','', '6', '1', '1'),
(null,'Investigar essência através de autorreflexão','', '6', '1', '1'),
(null,'Abandonar necessidade de estar certo','', '6', '1', '1'),
(null,'Cortar pensamentos negativos','', '6', '1', '1'),
(null,'Agradecer mentalmente pessoas que incomodam','', '6', '3', '1'),
(null,'Não alimentar julgamentos mentais','', '6', '3', '1'),
(null,'Estudar novo testamento Bíblia','', '6', '3', '1'),
(null,'Estudar Bhagavad Gita','', '6', '3', '1'),
(null,'Estudar outra língua','', '6', '3', '1'),
(null,'Definir cultura empresarial','', '6', '2', '1'),
(null,'Envolver colaboradores em todos os níveis da vida','', '6', '3', '1'),
(null,'Alinhar propósitos pessoais com empresariais/profissionais','', '6', '2', '1'),
(null,'Investir em ideias / genialidade','', '6', '2', '1'),
(null,'Contribuir para próximas gerações','', '6', '2', '1'),
(null,'Inspirar futuras lideranças','', '6', '2', '1'),
(null,'Ser pontual','', '6', '2', '1'),
(null,'Não estender horário de almoço','', '6', '1', '1'),
(null,'Não diminuir horário de almoço','', '6', '1', '1'),
(null,'Diminuir tempo e conversas às idas ao café','', '6', '1', '1'),
(null,'Cortar fofocas','', '6', '2', '1'),
(null,'Não estimular assuntos nocivos','', '6', '1', '1'),
(null,'Respeitar a visão do próximo','', '6', '1', '1'),
(null,'Estudar sobre cultura empresarial / cases de grades empresas e profissionais','', '6', '1', '1'),
(null,'Realizar treinamento de alto impacto / mudança de cultura empresarial','', '6', '3', '1')