INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Servir quem precisa e pede','', '7', '3', '1'),
(null,'Agradecer continuamente','', '7', '3', '1'),
(null,'Agradecer antes das refeições e realizá-las de maneira consciente','', '7', '3', '1'),
(null,'Plantar árvores / flores','', '7', '3', '1'),
(null,'Adotar um animal','', '7', '3', '1'),
(null,'Estudar espiritualidade pessoal','', '7', '3', '1'),
(null,'Assistir filme espiritual','', '7', '3', '1'),
(null,'Fazer Yoga  / Aikidô  / Tai Chi','', '7', '3', '1'),
(null,'Referir-se a classes (motoboy, gari, mulher, negro) como seres humanos','', '7', '3', '1'),
(null,'Referir-se a insetos como seres vivos','', '7', '3', '1'),
(null,'Caminhar com atenção e observação','', '7', '3', '1'),
(null,'Tornar-se na prática sua própria filosofia de vida (missão, visão e valores)','', '7', '3', '1'),
(null,'Observar / contemplar situações desafiadoras','', '7', '3', '1'),
(null,'Fazer caridade através de serviço presencial','', '7', '3', '1'),
(null,'Meditar','', '7', '3', '1'),
(null,'Realizar ação social ou ambiental sem divulgar','', '7', '3', '1'),
(null,'Fazer jejum prolongado 4+ dias','', '7', '3', '1'),
(null,'Observar ingestão de carnes / álcool','', '7', '3', '1'),
(null,'Contemplar situações da vida','', '7', '3', '1'),
(null,'Fazer O Curso Em Milagres ','', '7', '3', '1'),
(null,'Ouvir música espiritual','', '7', '3', '1'),
(null,'Estudar processo dos 12 passos','', '7', '3', '1'),
(null,'Estudar novo testamento Bíblia','', '7', '3', '1'),
(null,'Estudar Cânone Pali','', '7', '3', '1'),
(null,'Estudar Bhagavad Gita','', '7', '3', '1'),
(null,'Estudar Vedas e Upanishads','', '7', '3', '1'),
(null,'Estudar Tao Te Ching','', '7', '3', '1'),
(null,'Dar um nome / forma para seu ego','', '7', '3', '1'),
(null,'Convidar pessoas para seu local de oração/meditação','', '7', '3', '1'),
(null,'Usar apenas materiais reciclados','', '7', '3', '1'),
(null,'Fazer pergunta e aguardar resposta','', '7', '3', '1'),
(null,'Implantar plano de sustentabilidade','', '7', '3', '1'),
(null,'Implantar plano de contribuição social','', '7', '3', '1'),
(null,'Se empenhar na reciclagem de materiais','', '7', '3', '1'),
(null,'Contribuir com caridade de excedentes internos','', '7', '3', '1'),
(null,'Resolver situações dentro das competências, independente de remuneração','', '7', '3', '1'),
(null,'Integrar pessoa-empresa-sociedade','', '7', '3', '1'),
(null,'Propagar a harmonia no ambiente de trabalho','', '7', '3', '1'),
(null,'Agradecer mesmo quando parecer desconfortável ou negativo','', '7', '3', '1'),
(null,'Aprender com os seus erros e dos outros','', '7', '3', '1'),
(null,'Encarar os problemas com alegria e bom humor','', '7', '3', '1'),
(null,'Emanar cura e amor','', '7', '3', '1'),
(null,'Estudar sobre espiritualidade / líderes espirituais / legados empresariais','', '7', '3', '1'),
(null,'Realizar retiros espirituais','', '7', '3', '1')