INSERT INTO iap_desafio (id, titulo, descricao, nivel, yy, publicado) 

VALUES 

(null,'Ensinar algo a alguém','', '5', '2', '1'),
(null,'Olhar nos olhos enquanto conversa','', '5', '2', '1'),
(null,'Pedir permissão para falar de outro','', '5', '2', '1'),
(null,'Só falar a verdade','', '5', '2', '1'),
(null,'Não fazer piadas ou praticar bullying com os outros','', '5', '2', '1'),
(null,'Pedir desculpas','', '5', '2', '1'),
(null,'Falar quando quer silenciar','', '5', '2', '1'),
(null,'Priorizar comunicação para: ao vivo <- telefone <- digital','', '5', '2', '1'),
(null,'Cruzar habilidades que tem com atividades que gosta','', '5', '2', '1'),
(null,'Escrever artigos ou poemas e publicar em blog ou redes sociais','', '5', '2', '1'),
(null,'Mandar mensagens de voz quando se comunicar','', '5', '2', '1'),
(null,'Agradecer pessoas que fazem pequenas tarefas no seu dia-a-dia','', '5', '2', '1'),
(null,'Ser gentil em todos os momentos','', '5', '2', '1'),
(null,'Pedir mais ajuda','', '5', '2', '1'),
(null,'Expressar ideias','', '5', '2', '1'),
(null,'Cortar fofocas','', '5', '2', '1'),
(null,'Cortar lisonjas e puxa-saquismo a outros','', '5', '2', '1'),
(null,'Não-julgar verbalmente','', '5', '1', '1'),
(null,'Deixar de tentar convencer pessoas','', '5', '1', '1'),
(null,'Cortar manipulação com palavras e gestos','', '5', '1', '1'),
(null,'Silenciar quando precisa falar','', '5', '1', '1'),
(null,'Ficar em silêncio','', '5', '1', '1'),
(null,'Criar própria filosofia de vida (missão, visão e valores)','', '5', '1', '1'),
(null,'Retirar palavrões','', '5', '1', '1'),
(null,'Abster-se de jurar e prometer','', '5', '1', '1'),
(null,'Retirar palavras negativas: não consigo, mas, nunca, etc','', '5', '1', '1'),
(null,'Escutar sempre toda a resposta antes de responder','', '5', '1', '1'),
(null,'Respeitar tradições e crenças alheias','', '5', '1', '1'),
(null,'Olhar nos próprios olhos no espelho e dizer intenção para o dia','', '5', '3', '1'),
(null,'Pedir perdão/perdoar ativamente pessoa com conflito','', '5', '3', '1'),
(null,'Contemplar a própria morte e escrever carta','', '5', '3', '1'),
(null,'Não se justificar','', '5', '3', '1'),
(null,'Improvisar sempre que necessário','', '5', '3', '1'),
(null,'Responder negatividades das outras pessoas com positividades','', '5', '3', '1'),
(null,'Criar storytelling da empresa/ carreira','', '5', '2', '1'),
(null,'Criar artigos e postar em blogs / mídias sociais / revistas','', '5', '2', '1'),
(null,'Criar vídeos de conteúdos gratuitos','', '5', '2', '1'),
(null,'Desenvolver líderes/liderança pessoal','', '5', '2', '1'),
(null,'Motivar fidelização empresarial','', '5', '2', '1'),
(null,'Pedir desculpas','', '5', '1', '1'),
(null,'Dar ideias de melhorias aos colegas','', '5', '2', '1'),
(null,'Dar feedbakcs sobre os problemas aos líderes ou liderados','', '5', '2', '1'),
(null,'Melhorar comunicação com outros departamentos','', '5', '2', '1'),
(null,'Responder mais rápido a pedidos','', '5', '2', '1'),
(null,'Estudar sobre planejamento estratégico / fidelização / autobiografias','', '5', '2', '1'),
(null,'Realizar treinamento de liderança / comunicação não-agressiva','', '5', '3', '1')